# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5cfc788bbf934d707c4e1e22e5f0b4988b5e715a8457b5902ee9a9f516958b2b3c553d4cb5b3adb62ec0537aaf2cfe00baefe995c816b7d25cf43aea7228cf

test:
  secret_key_base: 2885222d2637b228a35e0f7abdc0ddb1ca6a53536993eb020dd0a88992dc60a9984e1808d4947fc3e61d7416882e051c2bc2aaafc927e07996a8b204f7d194ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
